name: Detect eval and exec errors

on:
  push:
    branches:
      - main

jobs:
  find-eval-exec-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Find eval and exec files
        run: python find_eval_exec_files.py

      - name: Report errors
        if: ${{ steps.find-eval-exec-files.outputs.files.length > 0 }}
        run: |
          echo "The following files use eval or exec:"
          for file in ${{ steps.find-eval-exec-files.outputs.files }}:
            echo "  $file"
        report: false    
            
